### ISSUE TITLE
Unable to run on EndeavourOS

### ISSUE THREAD

**Issue by nstdio** [zzkW35/amdgpu-fan#13]
```sh
$ sudo amdgpu-fan

starting amdgpu-fan
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/amdgpu-fan", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/amdgpu_fan/controller.py", line 95, in main
    FanController(config).main()
  File "/usr/lib/python3.11/site-packages/amdgpu_fan/controller.py", line 49, in main
    card.set_fan_speed(speed)
  File "/usr/lib/python3.11/site-packages/amdgpu_fan/lib/amdgpu.py", line 77, in set_fan_speed
    return self.write_endpoint('pwm1', int(speed))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/amdgpu_fan/lib/amdgpu.py", line 41, in write_endpoint
    with open(self._endpoints[endpoint], 'w') as e:
OSError: [Errno 22] Invalid argument
```

The `self._endpoints` is

```
{
  'temp3_crit': '/sys/class/drm/card1/device/hwmon/hwmon3/temp3_crit',
  'temp2_crit': '/sys/class/drm/card1/device/hwmon/hwmon3/temp2_crit',
  'freq1_label': '/sys/class/drm/card1/device/hwmon/hwmon3/freq1_label',
  'temp3_crit_hyst': '/sys/class/drm/card1/device/hwmon/hwmon3/temp3_crit_hyst',
  'temp3_input': '/sys/class/drm/card1/device/hwmon/hwmon3/temp3_input',
  'in0_input': '/sys/class/drm/card1/device/hwmon/hwmon3/in0_input',
  'power1_label': '/sys/class/drm/card1/device/hwmon/hwmon3/power1_label',
  'temp2_emergency': '/sys/class/drm/card1/device/hwmon/hwmon3/temp2_emergency',
  'fan1_min': '/sys/class/drm/card1/device/hwmon/hwmon3/fan1_min',
  'temp1_label': '/sys/class/drm/card1/device/hwmon/hwmon3/temp1_label',
  'temp1_crit': '/sys/class/drm/card1/device/hwmon/hwmon3/temp1_crit',
  'pwm1_enable': '/sys/class/drm/card1/device/hwmon/hwmon3/pwm1_enable',
  'pwm1': '/sys/class/drm/card1/device/hwmon/hwmon3/pwm1',
  'temp1_crit_hyst': '/sys/class/drm/card1/device/hwmon/hwmon3/temp1_crit_hyst',
  'power1_cap_min': '/sys/class/drm/card1/device/hwmon/hwmon3/power1_cap_min',
  'fan1_enable': '/sys/class/drm/card1/device/hwmon/hwmon3/fan1_enable',
  'fan1_max': '/sys/class/drm/card1/device/hwmon/hwmon3/fan1_max',
  'freq2_label': '/sys/class/drm/card1/device/hwmon/hwmon3/freq2_label',
  'power1_cap': '/sys/class/drm/card1/device/hwmon/hwmon3/power1_cap',
  'pwm1_min': '/sys/class/drm/card1/device/hwmon/hwmon3/pwm1_min',
  'power1_average': '/sys/class/drm/card1/device/hwmon/hwmon3/power1_average',
  'freq1_input': '/sys/class/drm/card1/device/hwmon/hwmon3/freq1_input',
  'power1_cap_max': '/sys/class/drm/card1/device/hwmon/hwmon3/power1_cap_max',
  'temp2_label': '/sys/class/drm/card1/device/hwmon/hwmon3/temp2_label',
  'fan1_input': '/sys/class/drm/card1/device/hwmon/hwmon3/fan1_input',
  'power1_cap_default': '/sys/class/drm/card1/device/hwmon/hwmon3/power1_cap_default',
  'temp1_input': '/sys/class/drm/card1/device/hwmon/hwmon3/temp1_input',
  'pwm1_max': '/sys/class/drm/card1/device/hwmon/hwmon3/pwm1_max',
  'temp3_emergency': '/sys/class/drm/card1/device/hwmon/hwmon3/temp3_emergency',
  'fan1_target': '/sys/class/drm/card1/device/hwmon/hwmon3/fan1_target',
  'temp2_crit_hyst': '/sys/class/drm/card1/device/hwmon/hwmon3/temp2_crit_hyst',
  'freq2_input': '/sys/class/drm/card1/device/hwmon/hwmon3/freq2_input',
  'temp3_label': '/sys/class/drm/card1/device/hwmon/hwmon3/temp3_label',
  'temp1_emergency': '/sys/class/drm/card1/device/hwmon/hwmon3/temp1_emergency',
  'in0_label': '/sys/class/drm/card1/device/hwmon/hwmon3/in0_label',
  'name': '/sys/class/drm/card1/device/hwmon/hwmon3/name',
  'temp2_input': '/sys/class/drm/card1/device/hwmon/hwmon3/temp2_input'
}
```

and requested endpoint is `pwm1` which points to `/sys/class/drm/card1/device/hwmon/hwmon3/pwm1` file.

```sh
$ cat /sys/class/drm/card1/device/hwmon/hwmon3/pwm1
0
```

**Comment by nstdio** [comment]
Apparently driver does not have support for configuring fan speed.
