### ISSUE TITLE
KeyError: 'pwm1_min' and can't start service

### ISSUE THREAD

**Issue by All3xJ** [zzkW35/amdgpu-fan#3]
Hello. I have a Huawei Matebook D 14 2020. AMD Ryzen 5 3500U with Vega GPU.

I installed amdgpu-fan via AUR: https://aur.archlinux.org/packages/amdgpu-fan/
The I started it with systemctl, but it fails.

Here is the output of systemctl status amdgpu-fan:

```
× amdgpu-fan.service - amdgpu fan controller
     Loaded: loaded (/usr/lib/systemd/system/amdgpu-fan.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2021-05-06 15:30:53 CEST; 34s ago
    Process: 2856 ExecStart=/usr/bin/amdgpu-fan (code=exited, status=1/FAILURE)
   Main PID: 2856 (code=exited, status=1/FAILURE)
        CPU: 170ms

mag 06 15:30:53 Archy systemd[1]: amdgpu-fan.service: Scheduled restart job, restart counter is at 5.
mag 06 15:30:53 Archy systemd[1]: Stopped amdgpu fan controller.
mag 06 15:30:53 Archy systemd[1]: amdgpu-fan.service: Start request repeated too quickly.
mag 06 15:30:53 Archy systemd[1]: amdgpu-fan.service: Failed with result 'exit-code'.
mag 06 15:30:53 Archy systemd[1]: Failed to start amdgpu fan controller.
```

this is the output of journalctl -e -u amdgpu-fan:
```
mag 06 15:30:51 Archy amdgpu-fan[2853]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/lib/amdgpu.py", line 36, in read_endpoint
mag 06 15:30:51 Archy amdgpu-fan[2853]:     with open(self._endpoints[endpoint], 'r') as e:
mag 06 15:30:51 Archy amdgpu-fan[2853]: KeyError: 'pwm1_min'
mag 06 15:30:51 Archy systemd[1]: amdgpu-fan.service: Main process exited, code=exited, status=1/FAILURE
mag 06 15:30:51 Archy systemd[1]: amdgpu-fan.service: Failed with result 'exit-code'.
mag 06 15:30:52 Archy systemd[1]: amdgpu-fan.service: Scheduled restart job, restart counter is at 3.
mag 06 15:30:52 Archy systemd[1]: Stopped amdgpu fan controller.
mag 06 15:30:52 Archy systemd[1]: Started amdgpu fan controller.
mag 06 15:30:52 Archy amdgpu-fan[2854]: starting amdgpu-fan
mag 06 15:30:52 Archy amdgpu-fan[2854]: Traceback (most recent call last):
mag 06 15:30:52 Archy amdgpu-fan[2854]:   File "/usr/bin/amdgpu-fan", line 33, in <module>
mag 06 15:30:52 Archy amdgpu-fan[2854]:     sys.exit(load_entry_point('amdgpu-fan==0.1.0', 'console_scripts', 'amdgpu-fan')())
mag 06 15:30:52 Archy amdgpu-fan[2854]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/controller.py", line 95, in main
mag 06 15:30:52 Archy amdgpu-fan[2854]:     FanController(config).main()
mag 06 15:30:52 Archy amdgpu-fan[2854]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/controller.py", line 47, in main
mag 06 15:30:52 Archy amdgpu-fan[2854]:     logger.debug(f'{name}: Temp {temp}, Setting fan speed to: {speed}, fan speed: {card.fan_speed}, min: {card.fan_min}, max: {card.fan_max}')
mag 06 15:30:52 Archy amdgpu-fan[2854]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/lib/amdgpu.py", line 64, in fan_min
mag 06 15:30:52 Archy amdgpu-fan[2854]:     return int(self.read_endpoint('pwm1_min'))
mag 06 15:30:52 Archy amdgpu-fan[2854]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/lib/amdgpu.py", line 36, in read_endpoint
mag 06 15:30:52 Archy amdgpu-fan[2854]:     with open(self._endpoints[endpoint], 'r') as e:
mag 06 15:30:52 Archy amdgpu-fan[2854]: KeyError: 'pwm1_min'
mag 06 15:30:52 Archy systemd[1]: amdgpu-fan.service: Main process exited, code=exited, status=1/FAILURE
mag 06 15:30:52 Archy systemd[1]: amdgpu-fan.service: Failed with result 'exit-code'.
mag 06 15:30:52 Archy systemd[1]: amdgpu-fan.service: Scheduled restart job, restart counter is at 4.
mag 06 15:30:52 Archy systemd[1]: Stopped amdgpu fan controller.
mag 06 15:30:52 Archy systemd[1]: Started amdgpu fan controller.
mag 06 15:30:52 Archy amdgpu-fan[2856]: starting amdgpu-fan
mag 06 15:30:52 Archy amdgpu-fan[2856]: Traceback (most recent call last):
mag 06 15:30:52 Archy amdgpu-fan[2856]:   File "/usr/bin/amdgpu-fan", line 33, in <module>
mag 06 15:30:52 Archy amdgpu-fan[2856]:     sys.exit(load_entry_point('amdgpu-fan==0.1.0', 'console_scripts', 'amdgpu-fan')())
mag 06 15:30:52 Archy amdgpu-fan[2856]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/controller.py", line 95, in main
mag 06 15:30:52 Archy amdgpu-fan[2856]:     FanController(config).main()
mag 06 15:30:52 Archy amdgpu-fan[2856]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/controller.py", line 47, in main
mag 06 15:30:52 Archy amdgpu-fan[2856]:     logger.debug(f'{name}: Temp {temp}, Setting fan speed to: {speed}, fan speed: {card.fan_speed}, min: {card.fan_min}, max: {card.fan_max}')
mag 06 15:30:52 Archy amdgpu-fan[2856]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/lib/amdgpu.py", line 64, in fan_min
mag 06 15:30:52 Archy amdgpu-fan[2856]:     return int(self.read_endpoint('pwm1_min'))
mag 06 15:30:52 Archy amdgpu-fan[2856]:   File "/usr/lib/python3.9/site-packages/amdgpu_fan/lib/amdgpu.py", line 36, in read_endpoint
mag 06 15:30:52 Archy amdgpu-fan[2856]:     with open(self._endpoints[endpoint], 'r') as e:
mag 06 15:30:52 Archy amdgpu-fan[2856]: KeyError: 'pwm1_min'
mag 06 15:30:52 Archy systemd[1]: amdgpu-fan.service: Main process exited, code=exited, status=1/FAILURE
mag 06 15:30:52 Archy systemd[1]: amdgpu-fan.service: Failed with result 'exit-code'.
mag 06 15:30:53 Archy systemd[1]: amdgpu-fan.service: Scheduled restart job, restart counter is at 5.
mag 06 15:30:53 Archy systemd[1]: Stopped amdgpu fan controller.
mag 06 15:30:53 Archy systemd[1]: amdgpu-fan.service: Start request repeated too quickly.
mag 06 15:30:53 Archy systemd[1]: amdgpu-fan.service: Failed with result 'exit-code'.
mag 06 15:30:53 Archy systemd[1]: Failed to start amdgpu fan controller.
```

**Comment by roggif** [comment]
Hi there!
This package is meant to control fan speeds of a **dedicated** GPU card.
This means that in most of the cases it isn't really suited for laptops, since most of the times graphics cards in laptops share the same fan with the CPU. In your specific case the _Huawei Matebook D 14 2020_ doesn't even have a dedicated graphics card, the Radeon Vega 8 is integrated inside the CPU.

Here's my suggestion: if your PC allows it you can edit the fan curve within the BIOS, otherwise you should be looking for a **CPU** fan curve controller.

**Comment by All3xJ** [comment]
> Hi there!
> This package is meant to control fan speeds of a **dedicated** GPU card.
> This means that in most of the cases it isn't really suited for laptops, since most of the times graphics cards in laptops share the same fan with the CPU. In your specific case the _Huawei Matebook D 14 2020_ doesn't even have a dedicated graphics card, the Radeon Vega 8 is integrated inside the CPU.
> 
> Here's my suggestion: if your PC allows it you can edit the fan curve within the BIOS, otherwise you should be looking for a **CPU** fan curve controller.

thanks, but if I try to do run pwmconfig, its says that there are not pwm-capable sensors modules installed, so basically I can't manage fan in any way.

```
$ sudo pwmconfig
# pwmconfig version 3.6.0+git
This program will search your sensors for pulse width modulation (pwm)
controls, and test each one to see if it controls a fan on
your motherboard. Note that many motherboards do not have pwm
circuitry installed, even if your sensor chip supports pwm.

We will attempt to briefly stop each fan using the pwm controls.
The program will attempt to restore each fan to full speed
after testing. However, it is ** very important ** that you
physically verify that the fans have been to full speed
after the program has completed.

/usr/bin/pwmconfig: There are no pwm-capable sensor modules installed
```

what do you think I can do?
